name: Docker Image CI

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zerrissen/wintec-it-bot:latest
    - name: Public Docker image
      run: |
        docker login -u Zerrissen -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push zerrissen/wintec-it-bot:latest
