name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zerrissen/wintec-it-bot:latest
    - name: Public Docker image
      run: docker push zerrissen/wintec-it-bot:latest
